// Generado por herramientas/catalogo_a_json.py — no editar a mano
window.CATALOGO_EJEMPLO = {
  "empresa": {
    "nombre": "Distribuidor Ejemplo S.L.",
    "logo_archivo": "logo.png",
    "moneda": "EUR",
    "iva": 21,
    "version_catalogo": "0.1",
    "fecha": "2026-09-24",
    "condiciones_de_pago": "30 % a la firma, 70 % antes de la carga",
    "plazo_de_entrega": "10–12 semanas desde pedido",
    "garantias": "Estructura 10 años; film según ficha del fabricante",
    "no_incluido": "Obra civil, permisos, acometidas, equipamiento interior"
  },
  "modelos": [
    {
      "id": "MT-GOT-80",
      "nombre": "Multitúnel gótico 8,00 m",
      "familia": "multitunel",
      "anchos_de_nave_admitidos": "8",
      "separaciones_entre_porticos": "4",
      "alturas_a_canal_admitidas": "4.5;4;5",
      "flecha_del_arco": 1.8,
      "max_naves": 15,
      "max_longitud": 120,
      "viento_cerrado": 94,
      "viento_abierto": 130,
      "nieve": 0,
      "cultivo_colgado": 15,
      "equipamiento": 15,
      "ancho_hoja_cenital": 1.2,
      "sep_pilares_hastial": 4,
      "arriostramiento": 25,
      "garantia_estructura": 10,
      "descripcion": "Multitúnel gótico de 8 m de capilla, versión económica para hortícola.",
      "origen": "estimado"
    },
    {
      "id": "MT-GOT-96",
      "nombre": "Multitúnel gótico 9,60 m",
      "familia": "multitunel",
      "anchos_de_nave_admitidos": "9.6",
      "separaciones_entre_porticos": "4",
      "alturas_a_canal_admitidas": "4.5;5",
      "flecha_del_arco": 2,
      "max_naves": 15,
      "max_longitud": 120,
      "viento_cerrado": 94,
      "viento_abierto": 130,
      "nieve": 0,
      "cultivo_colgado": 15,
      "equipamiento": 15,
      "ancho_hoja_cenital": 1.5,
      "sep_pilares_hastial": 3.2,
      "arriostramiento": 30,
      "garantia_estructura": 10,
      "descripcion": "Multitúnel gótico de 9,6 m de capilla, mayor volumen de aire y luz.",
      "origen": "estimado"
    }
  ],
  "perfiles": [
    {
      "id": "PIL-100x50",
      "uso": "Pilar principal",
      "tipo": "rectangular",
      "medidas": "100×50",
      "espesor": 2.5,
      "peso": 5.9,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.4,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "PIL-120x60",
      "uso": "Pilar principal (9,6 m)",
      "tipo": "rectangular",
      "medidas": "120×60",
      "espesor": 3,
      "peso": 8.5,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.4,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "ARC-42",
      "uso": "Arco",
      "tipo": "redondo",
      "medidas": "Ø42",
      "espesor": 2,
      "peso": 1.97,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.4,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "ARC-48",
      "uso": "Arco (9,6 m)",
      "tipo": "redondo",
      "medidas": "Ø48",
      "espesor": 2,
      "peso": 2.27,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.4,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "TUB-32",
      "uso": "Cercha / tirante",
      "tipo": "redondo",
      "medidas": "Ø32",
      "espesor": 1.5,
      "peso": 1.13,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.4,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "TUB-25",
      "uso": "Correa",
      "tipo": "redondo",
      "medidas": "Ø25",
      "espesor": 1.5,
      "peso": 0.87,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.4,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "CAN-2",
      "uso": "Canal",
      "tipo": "canal",
      "medidas": "desarrollo 500",
      "espesor": 2,
      "peso": 7.85,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.5,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "CAN-25",
      "uso": "Canal (9,6 m)",
      "tipo": "canal",
      "medidas": "desarrollo 500",
      "espesor": 2.5,
      "peso": 9.8,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.5,
      "unidad_precio": "kg",
      "origen": "estimado"
    },
    {
      "id": "HAS-60x40",
      "uso": "Pilar de hastial",
      "tipo": "rectangular",
      "medidas": "60×40",
      "espesor": 2,
      "peso": 3.14,
      "grado_acero": "Q235",
      "galvanizado": "80",
      "precio": 1.4,
      "unidad_precio": "kg",
      "origen": "estimado"
    }
  ],
  "componentes": [
    {
      "id": "C01",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Pilares principales",
      "ref": "PIL-100x50|PIL-120x60",
      "unidad": "kg",
      "regla": "por_pilar",
      "factor": "altura_canal",
      "tipo": "obligatorio",
      "texto_propuesta": "Pilares de acero galvanizado en caliente",
      "origen": "estimado"
    },
    {
      "id": "C02",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Arcos",
      "ref": "ARC-42|ARC-48",
      "unidad": "kg",
      "regla": "por_portico_nave",
      "factor": "arco",
      "tipo": "obligatorio",
      "texto_propuesta": "Arcos góticos galvanizados",
      "origen": "estimado"
    },
    {
      "id": "C03",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Cerchas y tirantes",
      "ref": "TUB-32",
      "unidad": "kg",
      "regla": "por_portico_nave",
      "factor": "ancho_nave*1.8",
      "tipo": "obligatorio",
      "texto_propuesta": "Cercha con cordón inferior y diagonales",
      "origen": "estimado"
    },
    {
      "id": "C04",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Correas",
      "ref": "TUB-25",
      "unidad": "kg",
      "regla": "lineas_x_longitud",
      "factor": "naves*5|naves*6",
      "tipo": "obligatorio",
      "texto_propuesta": "Correas longitudinales",
      "origen": "estimado"
    },
    {
      "id": "C05",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Canales",
      "ref": "CAN-2|CAN-25",
      "unidad": "kg",
      "regla": "lineas_x_longitud",
      "factor": "naves+1",
      "tipo": "obligatorio",
      "texto_propuesta": "Canal de chapa galvanizada",
      "origen": "estimado"
    },
    {
      "id": "C06",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Pilares de hastial",
      "ref": "HAS-60x40",
      "unidad": "kg",
      "regla": "por_pilar_hastial",
      "factor": "altura_canal",
      "tipo": "obligatorio",
      "texto_propuesta": "Pilares de frontales",
      "origen": "estimado"
    },
    {
      "id": "C09",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Arriostramientos",
      "unidad": "kg",
      "regla": "formula",
      "formula_avanzada": "(4+2*ceil(tramos/5))*kg_arriostramiento",
      "tipo": "obligatorio",
      "precio_unitario": 1.4,
      "texto_propuesta": "Arriostramientos de cubierta y laterales",
      "origen": "estimado"
    },
    {
      "id": "C07",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Anclajes",
      "unidad": "ud",
      "regla": "formula",
      "formula_avanzada": "pilares+pilares_hastial",
      "tipo": "obligatorio",
      "precio_unitario": 6.0,
      "texto_propuesta": "Placas de anclaje",
      "origen": "estimado"
    },
    {
      "id": "C08",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Estructura",
      "nombre": "Tornillería",
      "unidad": "%",
      "regla": "porcentaje",
      "factor": "0.08",
      "tipo": "obligatorio",
      "texto_propuesta": "Tornillería y conectores galvanizados",
      "origen": "estimado"
    },
    {
      "id": "C10",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Cubierta",
      "nombre": "Film de techo",
      "ref": "FILM-200",
      "unidad": "m²",
      "regla": "superficie_cubierta",
      "factor": "1.10",
      "tipo": "obligatorio",
      "grupo_alternativas": "cubierta_techo",
      "texto_propuesta": "Film PE tricapa 200 µm",
      "origen": "estimado"
    },
    {
      "id": "C11",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Cubierta",
      "nombre": "Film lateral y frontal",
      "ref": "FILM-200",
      "unidad": "m²",
      "regla": "superficie_cerramiento",
      "factor": "1.10",
      "tipo": "obligatorio",
      "grupo_alternativas": "cerramiento",
      "texto_propuesta": "Film PE en laterales y frontales",
      "origen": "estimado"
    },
    {
      "id": "C12",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Cubierta",
      "nombre": "Perfil de sujeción",
      "unidad": "m",
      "regla": "formula",
      "formula_avanzada": "2*naves*largo+2*naves*arco+4*largo+4*ancho_total",
      "tipo": "obligatorio",
      "precio_unitario": 0.9,
      "texto_propuesta": "Perfil lock channel galvanizado",
      "origen": "estimado"
    },
    {
      "id": "C13",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Cubierta",
      "nombre": "Alambre zigzag",
      "unidad": "m",
      "regla": "formula",
      "formula_avanzada": "2*naves*largo+2*naves*arco+4*largo+4*ancho_total",
      "tipo": "obligatorio",
      "precio_unitario": 0.15,
      "texto_propuesta": "Alambre zigzag",
      "origen": "estimado"
    },
    {
      "id": "C20",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Ventilación",
      "nombre": "Ventana cenital una hoja",
      "ref": "VEN-CEN-1",
      "unidad": "m",
      "regla": "formula",
      "formula_avanzada": "naves*long_ventana_cenital",
      "tipo": "opcional",
      "grupo_alternativas": "ventilacion_cenital",
      "precio_unitario": 9.0,
      "texto_propuesta": "Ventana cenital continua motorizada, una hoja por nave",
      "origen": "estimado"
    },
    {
      "id": "C21",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Ventilación",
      "nombre": "Ventana cenital mariposa",
      "ref": "VEN-CEN-2",
      "unidad": "m",
      "regla": "formula",
      "formula_avanzada": "2*naves*long_ventana_cenital",
      "tipo": "opcional",
      "grupo_alternativas": "ventilacion_cenital",
      "precio_unitario": 9.0,
      "texto_propuesta": "Ventana cenital mariposa motorizada",
      "origen": "estimado"
    },
    {
      "id": "C22",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Ventilación",
      "nombre": "Motores cenitales",
      "ref": "MOT-90",
      "unidad": "ud",
      "regla": "por_ventana",
      "tipo": "obligatorio",
      "texto_propuesta": "Motorreductor cenital 230/400 V",
      "origen": "tienda"
    },
    {
      "id": "C23",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Ventilación",
      "nombre": "Enrollables laterales",
      "ref": "VEN-LAT",
      "unidad": "m",
      "regla": "formula",
      "formula_avanzada": "2*largo",
      "tipo": "opcional",
      "grupo_alternativas": "ventilacion_lateral",
      "precio_unitario": 3.0,
      "texto_propuesta": "Ventana lateral enrollable motorizada",
      "origen": "estimado"
    },
    {
      "id": "C26",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Ventilación",
      "nombre": "Motores laterales",
      "ref": "MOT-90",
      "unidad": "ud",
      "regla": "formula",
      "formula_avanzada": "2*ceil(largo/90)",
      "tipo": "obligatorio",
      "texto_propuesta": "Motorreductor de enrollable lateral",
      "origen": "tienda"
    },
    {
      "id": "C24",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Ventilación",
      "nombre": "Malla antiinsectos",
      "ref": "MALLA-20x10",
      "unidad": "m²",
      "regla": "formula",
      "formula_avanzada": "superficie_ventanas*1.1",
      "tipo": "obligatorio",
      "texto_propuesta": "Malla antiinsectos 20×10 en todas las ventanas",
      "origen": "estimado"
    },
    {
      "id": "C25",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Ventilación",
      "nombre": "Cuadro de control",
      "ref": "CUAD-1",
      "unidad": "ud",
      "regla": "fija",
      "factor": "1",
      "tipo": "obligatorio",
      "texto_propuesta": "Cuadro de maniobra de motores",
      "origen": "estimado"
    },
    {
      "id": "C30",
      "modelos": "MT-GOT-80;MT-GOT-96",
      "categoria": "Accesos",
      "nombre": "Puerta corredera 3×3 m",
      "ref": "PUE-3x3",
      "unidad": "ud",
      "regla": "fija",
      "factor": "puertas",
      "tipo": "obligatorio",
      "texto_propuesta": "Puerta corredera 3,0 × 3,0 m",
      "origen": "estimado"
    }
  ],
  "cubiertas": [
    {
      "id": "FILM-200",
      "tipo": "film",
      "nombre": "PE tricapa 200 µm anti-UV antigoteo",
      "espesor": "200 µm",
      "transmision_luz": 90,
      "difusion": 15,
      "garantia": 36,
      "precio": 0.45,
      "origen": "estimado"
    },
    {
      "id": "MALLA-20x10",
      "tipo": "malla",
      "nombre": "Malla antiinsectos 20×10 hilos/cm",
      "factor_paso_de_aire": 0.67,
      "precio": 0.35,
      "origen": "literatura"
    }
  ],
  "equipos": [
    {
      "id": "MOT-90",
      "tipo": "motor",
      "nombre": "Motor cenital hasta 90 m",
      "potencia": 250,
      "capacidad": 90,
      "par": 170,
      "precio": 449,
      "origen": "tienda"
    },
    {
      "id": "MOT-120",
      "tipo": "motor",
      "nombre": "Motor cenital hasta 120 m",
      "potencia": 550,
      "capacidad": 120,
      "par": 440,
      "precio": 593,
      "origen": "tienda"
    },
    {
      "id": "CUAD-1",
      "tipo": "cuadro",
      "nombre": "Cuadro de maniobra de motores",
      "precio": 600,
      "origen": "estimado"
    },
    {
      "id": "PUE-3x3",
      "tipo": "puerta",
      "nombre": "Puerta corredera 3,0 × 3,0 m",
      "ancho_puerta": 3,
      "alto_puerta": 3,
      "precio": 420,
      "origen": "estimado"
    },
    {
      "id": "VEN-CEN-1",
      "tipo": "ventana",
      "nombre": "Cenital de una hoja, cremallera",
      "lineas_por_nave": 1,
      "recorrido_cremallera": 1,
      "origen": "estimado"
    },
    {
      "id": "VEN-CEN-2",
      "tipo": "ventana",
      "nombre": "Cenital mariposa, cremallera",
      "lineas_por_nave": 2,
      "recorrido_cremallera": 1,
      "origen": "estimado"
    },
    {
      "id": "VEN-LAT",
      "tipo": "ventana",
      "nombre": "Lateral enrollable",
      "alto_ventana": 2,
      "origen": "estimado"
    }
  ],
  "obra_local": [
    {
      "zona": "Almería",
      "movilizacion": 1500,
      "montaje": 10,
      "hoyos_y_dados": 35,
      "origen": "estimado"
    }
  ]
};
